# -*- coding: utf-8 -*-
"""Personal_Detail_Gathering_Project_using_NLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqnvSLpqrofR9LJj9gJXoBc_a3G4Zu6F
"""

import re
pattern='\d{10}|\(\d{3}\)-\d{3}-\d{3}'
chat='9749877489,87894,(123)-567-878'
mat=re.findall(pattern,chat)
print(mat)

pattern2='[a-z0-9A-Z_\.]*@[a-z]*\.[a-zA-Z]*'
chat='basha.kkl1999@gmail.com,jdjkjlj,jijo3e'
mat1=re.findall(pattern2,chat)
print(mat1)

pattern3='Born(.*)'
chat3='''Born	Elon Reeve Musk
June 28, 1971 (age 51)
Pretoria, Transvaal, South Africa
Education	University of Pennsylvania (BA, BS)'''
mat3=re.findall(pattern3,chat3)
print(mat3[0].strip())

pattern4='June.*\n(.*)'
chat3='''Born	Elon Reeve Musk
June 28, 1971 (age 51)
Pretoria, Transvaal, South Africa
Education	University of Pennsylvania (BA, BS)'''
mat3=re.findall(pattern4,chat3)
print(mat3)

pattern5='\(age.*\n(.*)'
chat4='''Born	Elon Reeve Musk
June 28, 1971 (age 51)
Pretoria, Transvaal, South Africa
Education	University of Pennsylvania (BA, BS)'''
mat4=re.findall(pattern5,chat4)
print(mat4[0].strip())

def get_pattern_match(pattern, text):
  matches=re.findall(pattern, text)
  if matches:
    return matches[0]

get_pattern_match('\(age.*\n(.*)', chat4)

def get_personal_information(text):
  full_name=get_pattern_match('Born(.*)', text)
  birth_date=get_pattern_match('Born.*\n(.*)\(', text)
  birth_place=get_pattern_match('\(age.*\n(.*)', text)

  return {
      "name":full_name.strip(),
      "Birth_date":birth_date,
      "Birth_place":birth_place
  }

chat5='''Born	Elon Reeve Musk
June 28, 1971 (age 51)
Pretoria, Transvaal, South Africa
Education	University of Pennsylvania (BA, BS)'''
get_personal_information(chat5)

